version: '3'

services:
  gateway-server:
    build: .
    volumes:
      - .env:/app/.env
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    env_file:
      - ./.env
    networks:
      - bridged_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridged_network

volumes:
  postgres_data:

networks:
  bridged_network:
    driver: bridge